librocksdb-sys: Add support for building with io_uring on Linux.
rust-rocksdb/rust-rocksdb pull request #621
Opened 2022-03-17 14:16 UTC by parazyd

2022-05-02 08:12 UTC, aleksuss commented on librocksdb-sys/build.rs
> +        pkg_config::probe_library("liburing").unwrap();
What will be if there is no `liburing` library on a host?

```suggestion
        if pkg_config::probe_library("liburing").is_ok() {
            config.define("ROCKSDB_IOURING_PRESENT", Some("1"));
        }
```

2022-05-02 08:12 UTC, aleksuss commented on librocksdb-sys/build.rs
> +        pkg_config::probe_library("liburing").unwrap();
What will be if there is no `liburing` library on a host?

```suggestion
        if pkg_config::probe_library("liburing").is_ok() {
            config.define("ROCKSDB_IOURING_PRESENT", Some("1"));
        }
```

2022-05-02 08:45 UTC, aleksuss commented
It would be good to add a new job in a CI for checking this feature.

2022-05-02 09:12 UTC, parazyd commented
@aleksuss I thought it's better not to silently fall through if the feature is explicitly enabled but the library is unavailable. Would you like me to chane this?

2022-05-02 09:53 UTC, aleksuss commented
Then you probably should add a message to inform a user: 
```rust
pkg_config::probe_library("liburing").except("The io_uring feature was provided but the library was not found");
```
or something...

2022-05-02 10:26 UTC, parazyd commented
Updated. Thanks.

2022-08-05 08:23 UTC, aleksuss requested changes
Fix the typo in method `expect` please.

2022-08-05 08:23 UTC, aleksuss commented on librocksdb-sys/build.rs
> +    if target.contains("linux") && cfg!(feature = "io-uring") {
```suggestion
    #[cfg(feature = "io-uring")]
    if target.contains("linux") && cfg!(feature = "io-uring") {
```

2022-08-05 08:23 UTC, aleksuss commented on librocksdb-sys/build.rs
> +            .except("The io-uring feature was requested but the library is not available");
```suggestion
            .expect("The io-uring feature was requested but the library is not available");
```

2022-08-05 10:47 UTC, stanislav-tkach approved these changes

2022-08-05 11:16 UTC, aleksuss approved these changes

2022-08-05 12:01 UTC, merged